import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ExampleQueryQuery, getBuiltGraphSDK } from '../.graphclient'

const Home: NextPage<{ data: ExampleQueryQuery }> = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Graph Client Next.js Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Graph Client <a href="https://nextjs.org">Next.js</a> Example
        </h1>

        <form>
          <label>Data</label>
          <br />
          <textarea className={styles.dataTextArea} value={JSON.stringify(data, null, 2)} readOnly rows={55} />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

const sdk = getBuiltGraphSDK()
export async function getServerSideProps() {
  const data = await sdk.ExampleQuery()
  return {
    props: {
      data,
    },
  }
}

export default Home
