sources:
  - name: uniswapv2
    handler:
      graphql:
        strategy: fallback
        sources:
          - endpoint: https://bad-uniswap-v2-api.com
            retry: 2
          - endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
  - name: compoundv2
    handler:
      graphql:
        strategy: fallback
        sources:
          - endpoint: https://bad-compund-v2-api.com
            retry: 2
          - endpoint: https://api.thegraph.com/subgraphs/name/graphprotocol/compound-v2
