sources:
  - name: uniswap
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    transforms:
      # Enable Automatic Block Tracking
      - autoPagination:
          validateSchema: true

serve:
  browser: false
