sources:
  - name: nft
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/amxx/eip721-subgraph

    transforms:
      # Rename Account to User to apply Type Merging between NFT's Account and UNI's User
      - rename:
          - from:
              type: Account
            to:
              type: User
      - autoTypeMerging: true

  - name: uniswap
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
    transforms:
      - autoTypeMerging: true

documents:
  - ./example-query.graphql
