sources:
  - name: Protocol
    handler:
      graphql:
        # This is needed for the initial introspection on buildtime
        endpoint: https://api.thegraph.com/subgraphs/name/messari/{context.protocolName:curve-finance-ethereum}

additionalTypeDefs: |
  extend type LiquidityPool {
    protocolName: String
  }
  extend type Query {
    crossLiquidityPools(first: Int!, protocolNames: [String!]!, orderBy: BigDecimal!, orderDirection: OrderDirection!, where: LiquidityPool_filter!): [LiquidityPool!]!
  }

  extend type LiquidityPoolDailySnapshot {
    FeesUSD: BigDecimal
    TokenFeesUSD: BigDecimal
    TokenFeesRaw: BigDecimal
    RewardsPerToken: BigDecimal
    RewardsROI: BigDecimal
    FeesROI: BigDecimal
    BlockTimestamp: String
    DateInterval: String
  }

additionalResolvers:
  - ./src/resolvers-daily.ts
# - ./src/resolvers-hourly.ts

documents:
  - ./daily-query.graphql
# - ./hourly-query.graphql

codegen:
  contextType: 'MeshContext & { protocolName: string }'
