sources:
  - name: Uniswap
    handler:
      graphql:
        # Default value is uniswap-v2
        # This is needed for the initial introspection on buildtime
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/{context.chainId:uniswap-v2}

additionalTypeDefs: |
  extend type Pair {
    chainId: ID!
  }

additionalResolvers:
  - ./src/chainId.resolvers.ts

documents:
  - ./src/example-query.graphql
